Orderware\AppBundle\Entity\Item:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [division, itemNum]
            errorPath: itemNum
    properties:
        createdBy:
            - NotBlank: ~
        updatedBy:
            - NotBlank: ~
        statusId:
            - NotBlank: ~
        itemNum:
            - NotBlank: ~
            - Length:
                max: 36
            - Regex:
                pattern: '/^[A-Z0-9]+$/'
                message: "The item number must be alpha-numeric."
        displayName:
            - NotBlank: ~
        weight:
            - Range:
                min: 0.0
        length:
            - Range:
                min: 0.0
        width:
            - Range:
                min: 0.0
        depth:
            - Range:
                min: 0.0
        skus:
            - Valid: ~

Orderware\AppBundle\Entity\ItemSku:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [division, skucode]
            errorPath: skucode
    properties:
        item:
            - NotNull: ~
        createdBy:
            - NotBlank: ~
        updatedBy:
            - NotBlank: ~
        statusId:
            - NotBlank: ~
        skucode:
            - NotBlank: ~
            - Length:
                max: 36
            - Regex:
                pattern: '/^[A-Z0-9]+$/'
                message: "The skucode must be alpha-numeric."
        costPrice:
            - Type:
                type: integer
            - GreaterThanOrEqual:
                value: 0
        retailPrice:
            - Type:
                type: integer
            - GreaterThanOrEqual:
                value: 0
        pickDescription:
            - NotBlank: ~
            - Length:
                max: 100
        barcodes:
            - Valid: ~
