Orderware\AppBundle\Entity\Item:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
            fields: [account, itemNum]
            errorPath: itemNum
    properties:
        itemNum:
            - NotBlank: ~
        displayName:
            - NotBlank: ~
        attributes:
            - Valid: ~

Orderware\AppBundle\Entity\ItemAttribute:
    properties:
        attribute:
            - NotBlank: ~
        value:
            - NotBlank: ~
