imports:
    - { resource: config.yml }

framework:
    templating:
        assets_version: "%built_at%"

monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: "%kernel.root_dir%/../log/%kernel.environment%.log"
            level: debug
        console:
            type: console
