parameters: ~

services:
    # Global
    session.handler.redis:
        class: Drak\NativeSession\NativeRedisSessionHandler
        arguments: ["tcp://%redis_host%:%redis_port%?timeout=2&prefix=SESSION:"]

    redis:
        class: Redis
        calls:
            - [connect, ["%redis_host%", "%redis_port%"]]
