Orderware\AppBundle\Entity\Account:
    type: entity
    table: account
    id:
        account:
            type: string
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: string
        updatedBy:
            column: updated_by
            type: string
        statusId:
            column: status_id
            type: integer
        displayName:
            column: display_name
            type: string
        currency:
            column: currency
            type: string
        timeZone:
            column: time_zone
            type: string
        primaryEmail:
            column: primary_email
            type: string
            nullable: true
        notificationEmail:
            column: notification_email
            type: string
            nullable: true
        merchDescription:
            column: merch_description
            type: string
            nullable: true
    oneToMany:
        #items:
        #    targetEntity: Item
        #    mappedBy: account
        #    orderBy:
        #        itemNum: ASC
        #skus:
        #    targetEntity: ItemSku
        #    mappedBy: account
        #    orderBy:
        #        skucode: ASC
        vendors:
            targetEntity: Vendor
            mappedBy: account
            orderBy:
                vendorNum: ASC
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
