Orderware\AppBundle\Entity\Facility:
    type: entity
    table: facility
    id:
        facilityId:
            column: facility_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: facility_facility_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        facilityCode:
            column: facility_code
            type: text
        name:
            column: name
            type: text
        address1:
            column: address1
            type: text
            nullable: true
        address2:
            column: address2
            type: text
            nullable: true
        cityName:
            column: city_name
            type: text
            nullable: true
        stateName:
            column: state_name
            type: text
            nullable: true
        stateCode:
            column: state_code
            type: text
            nullable: true
        postalCode:
            column: postal_code
            type: text
            nullable: true
        countryName:
            column: country_name
            type: text
            nullable: true
        countryCode:
            column: country_code
            type: text
            nullable: true
        longitude:
            column: longitude
            type: decimal
        latitude:
            column: latitude
            type: decimal
        unitsPerDay:
            column: units_per_day
            type: integer
        isMaster: 
            column: is_master
            type: boolean
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
