Orderware\AppBundle\Entity\FeedLogEntry:
    type: entity
    table: feed_log_entry
    id:
        entryId:
            column: entry_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: feed_log_entry_entry_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: string
        updatedBy:
            column: updated_by
            type: string
        isError:
            column: is_error
            type: boolean
        message:
            column: message
            type: string
    manyToOne:
        feedLog:
            targetEntity: FeedLog
            inversedBy: entries
            joinColumn:
                name: log_id
                referencedColumnName: log_id
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
