Orderware\AppBundle\Entity\Feed:
    type: entity
    table: feed
    id:
        feedId:
            column: feed_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: feed_feed_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        statusId:
            column: status_id
            type: integer
        feedType:
            column: feed_type
            type: text
        fileName:
            column: file_name
            type: text
        fileSize:
            column: file_size
            type: integer
        fileHash:
            column: file_hash
            type: text
        manifest:
            column: manifest
            type: text
            nullable: true
        feedBody:
            column: feed_body
            type: text
            nullable: true
        errorMessage:
            column: error_message
            type: text
            nullable: true
        hasError:
            column: has_error
            type: boolean
        startedAt:
            column: started_at
            type: datetime
            nullable: true
        finishedAt:
            column: finished_at
            type: datetime
            nullable: true
        runTime:
            column: run_time
            type: integer
        memoryUsage:
            column: memory_usage
            type: integer
        recordCount:
            column: record_count
            type: integer
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
