Orderware\AppBundle\Entity\Feed:
    type: entity
    table: feed
    id:
        feedId:
            column: feed_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: feed_feed_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: string
        updatedBy:
            column: updated_by
            type: string
        statusId:
            column: status_id
            type: integer
        direction:
            column: direction
            type: string
        name:
            column: name
            type: string
        service:
            column: service
            type: string
        remoteRootDir:
            column: remote_root_dir
            type: string
        localRootDir:
            column: local_root_dir
            type: string
        filename:
            column: filename
            type: string
    manyToOne:
        connection:
            targetEntity: FeedConnection
            inversedBy: feeds
            joinColumn:
                name: connection_id
                referencedColumnName: connection_id
    oneToMany:
        attributes:
            targetEntity: FeedAttribute
            mappedBy: feed
            orderBy:
                attribute: ASC
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
