Orderware\AppBundle\Entity\FeedConfig:
    type: entity
    table: feed_config
    id:
        configId:
            column: configvendor_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: feed_config_config_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        name:
            column: name
            type: text
        version:
            column: version
            type: text
        direction:
            column: direction
            type: text
        service:
            column: service
            type: text
        serverHost:
            column: server_host
            type: text
            nullable: true
        serverPort:
            column: server_port
            type: integer
        serverUsername:
            column: server_username
            type: text
            nullable: true
        serverPrivateKey:
            column: server_private_key
            type: text
            nullable: true
        remoteDir:
            column: remote_dir
            type: text
            nullable: true
        localDir:
            column: local_dir
            type: text
            nullable: true
        environment:
            column: environment
            type: text
        filename:
            column: filename
            type: text
            nullable: true
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
