Orderware\AppBundle\Entity\Inventory:
    type: entity
    table: inventory
    id:
        inventoryId:
            column: inventory_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: inventory_inventory_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        qtyReceived:
            column: qty_received
            type: integer
        qtyOrdered:
            column: qty_ordered
            type: integer
        qtyShipped:
            column: qty_shipped
            type: integer
        qtyOnhand:
            column: qty_onhand
            type: integer
        qtyAvailable:
            column: qty_available
            type: integer
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
        facility:
            targetEntity: Facility
            joinColumn:
                name: facility_id
                referencedColumnName: facility_id
        sku:
            targetEntity: ItemSku
            joinColumn:
                name: sku_id
                referencedColumnName: sku_id
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
