Orderware\AppBundle\Entity\Item:
    type: entity
    table: item
    id:
        itemId:
            column: item_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: item_item_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: string
        updatedBy:
            column: updated_by
            type: string
        statusId:
            column: status_id
            type: integer
        itemNum:
            column: item_num
            type: string
        displayName:
            column: display_name
            type: string
        weight:
            column: weight
            type: decimal
        length:
            column: length
            type: decimal
        width:
            column: width
            type: decimal
        depth:
            column: depth
            type: decimal
        isShipAlone:
            column: is_ship_alone
            type: boolean
        isTaxable:
            column: is_taxable
            type: boolean
        isVirtual:
            column: is_virtual
            type: boolean
        trackInventory:
            column: track_inventory
            type: boolean
    manyToOne:
        account:
            targetEntity: Account
            inversedBy: items
            joinColumn:
                name: account
                referencedColumnName: account
    oneToMany:
        attributes:
            targetEntity: ItemAttribute
            mappedBy: item
            cascade: [persist, remove]
            orderBy:
                attribute: ASC
        #skus:
        #    targetEntity: ItemSku
        #    mappedBy: item
        #    cascade: [persist]
        #    orderBy:
        #        skucode: ASC
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
