Orderware\AppBundle\Entity\Item:
    type: entity
    table: item
    id:
        itemId:
            column: item_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: item_item_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        statusId:
            column: status_id
            type: integer
        itemNum:
            column: item_num
            type: text
        displayName:
            column: display_name
            type: text
        weight:
            column: weight
            type: decimal
        length:
            column: length
            type: decimal
        width:
            column: width
            type: decimal
        depth:
            column: depth
            type: decimal
        isShipAlone:
            column: is_ship_alone
            type: boolean
        isTaxable:
            column: is_taxable
            type: boolean
        isVirtual:
            column: is_virtual
            type: boolean
        trackInventory:
            column: track_inventory
            type: boolean
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
    oneToMany:
        skus:
            targetEntity: ItemSku
            mappedBy: item
            cascade: [persist]
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
