Orderware\AppBundle\Entity\ItemAttribute:
    type: entity
    table: item_attribute
    id:
        attributeId:
            column: attribute_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: item_attribute_attribute_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: string
        updatedBy:
            column: updated_by
            type: string
        key:
            column: key
            type: string
        value:
            column: value
            type: string
    manyToOne:
        item:
            targetEntity: Item
            inversedBy: attributes
            joinColumn:
                name: item_id
                referencedColumnName: item_id
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]

