Orderware\AppBundle\Entity\ItemSkuBarcode:
    type: entity
    table: item_sku_barcode
    id:
        barcodeId:
            column: barcode_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: item_sku_barcode_barcode_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        barcode:
            column: barcode
            type: text
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
        sku:
            targetEntity: ItemSku
            inversedBy: barcodes
            joinColumn:
                name: sku_id
                referencedColumnName: sku_id
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
