Orderware\AppBundle\Entity\ItemSku:
    type: entity
    table: item_sku
    id:
        skuId:
            column: sku_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: item_sku_sku_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        statusId:
            column: status_id
            type: integer
        skucode:
            column: skucode
            type: text
        costPrice:
            column: cost_price
            type: integer
        retailPrice:
            column: retail_price
            type: integer
        pickDescription:
            column: pick_description
            type: text
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
        item:
            targetEntity: Item
            inversedBy: skus
            joinColumn:
                name: item_id
                referencedColumnName: item_id
        vendor:
            targetEntity: Vendor
            joinColumn:
                name: vendor_id
                referencedColumnName: vendor_id
    oneToMany:
        barcodes:
            targetEntity: ItemSkuBarcode
            mappedBy: sku
            cascade: [persist]
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
