Orderware\AppBundle\Entity\Ledger:
    type: entity
    table: ledger
    id:
        ledgerId:
            column: ledger_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: ledger_ledger_id_seq
                allocationSize: 1
                initialValue: 1
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        statusId:
            column: status_id
            type: integer
        ledgerCode:
            column: ledger_code
            type: text
        invoicedAt:
            column: invoiced_at
            type: datetime
            nullable: true
        settledAt:
            column: settled_at
            type: datetime
            nullable: true
        canceledAt:
            column: canceled_at
            type: datetime
            nullable: true
        amount:
            column: amount
            type: integer
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
        order:
            targetEntity: OrdHeader
            inversedBy: ledgers
            joinColumn:
                name: ord_id
                referencedColumnName: ord_id
        line:
            targetEntity: OrdLine
            joinColumn:
                name: ord_line_id
                referencedColumnName: ord_line_id
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
