Orderware\AppBundle\Entity\OrdImport:
    type: entity
    table: ord_import
    id:
        importId:
            column: import_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: ord_import_import_id_seq
                allocationSize: 1
                initialValue: 1 
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        ordId:
            column: ord_id
            type: integer
            nullable: true
        statusId:
            column: status_id
            type: integer
        orderNum:
            column: order_num
            type: text
        orderBody:
            column: order_body
            type: text
        runTime:
            column: run_time
            type: integer
        memoryUsage:
            column: memory_usage
            type: integer
        errorMessage:
            column: error_message
            type: text
            nullable: true
        hasError:
            column: has_error
            type: boolean
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
