Orderware\AppBundle\Entity\OrdPay:
    type: entity
    table: ord_pay
    id:
        ordPayId:
            column: ord_pay_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: ord_pay_ord_pay_id_seq
                allocationSize: 1
                initialValue: 1
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        payMethod:
            column: pay_method
            type: text
        payAmount:
            column: pay_amount
            type: integer
        settledAmount:
            column: settled_amount
            type: integer
        transactionCode:
            column: transaction_code
            type: text
        currency:
            column: currency
            type: text
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
        order:
            targetEntity: OrdHeader
            inversedBy: payments
            joinColumn:
                name: ord_id
                referencedColumnName: ord_id
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
