Orderware\AppBundle\Entity\OrdShip:
    type: entity
    table: ord_ship
    id:
        ordShipId:
            column: ord_ship_id
            type: integer
            generator:
                strategy: SEQUENCE
            sequenceGenerator:
                sequenceName: ord_ship_ord_ship_id_seq
                allocationSize: 1
                initialValue: 1
    fields:
        createdAt:
            column: created_at
            type: datetime
        updatedAt:
            column: updated_at
            type: datetime
        createdBy:
            column: created_by
            type: text
        updatedBy:
            column: updated_by
            type: text
        shipMethod:
            column: ship_method
            type: text
        firstName:
            column: first_name
            type: text
            nullable: true
        middleName:
            column: middle_name
            type: text
            nullable: true
        lastName:
            column: last_name
            type: text
            nullable: true
        fullName:
            column: full_name
            type: text
            nullable: true
        address1:
            column: address1
            type: text
            nullable: true
        address2:
            column: address2
            type: text
            nullable: true
        cityName:
            column: city_name
            type: text
            nullable: true
        stateName:
            column: state_name
            type: text
            nullable: true
        stateCode:
            column: state_code
            type: text
            nullable: true
        postalCode:
            column: postal_code
            type: text
            nullable: true
        countryName:
            column: country_name
            type: text
            nullable: true
        countryCode:
            column: country_code
            type: text
            nullable: true
        companyName:
            column: company_name
            type: text
            nullable: true
        emailAddress:
            column: email_address
            type: text
            nullable: true
        phoneNumber:
            column: phone_number
            type: text
            nullable: true
        notifyBy:
            column: notify_by
            type: text
        notificationEnabled:
            column: notification_enabled
            type: boolean
        facilityCode:
            column: facility_code
            type: text
            nullable: true
    manyToOne:
        division:
            targetEntity: Division
            joinColumn:
                name: division
                referencedColumnName: division
        order:
            targetEntity: OrdHeader
            inversedBy: shipments
            joinColumn:
                name: ord_id
                referencedColumnName: ord_id
    oneToMany:
        lines:
            targetEntity: OrdLine
            mappedBy: shipment
            orderBy:
                lineNum: ASC
    lifecycleCallbacks:
        prePersist: [onCreate]
        preUpdate: [onUpdate]
