services:
    # Core
    #orderware.request_listener:
    #    class: Orderware\AppBundle\Listeners\RequestListener
    #    arguments: [@doctrine.orm.orderware_entity_manager]
    #    tags:
    #        - { name: kernel.event_listener, event: kernel.controller, method: onRequest }
    #        - { name: kernel.event_listener, event: kernel.response, method: onResponse }

    #orderware.exception_listener:
    #    class: Orderware\AppBundle\Listeners\ExceptionListener
    #    arguments: [@logger, @templating, @orderware.responder]
    #    tags:
    #        - { name: kernel.event_listener, event: kernel.exception, method: onException }

    # Internal
    #orderware.json_validator:
    #    class: Orderware\AppBundle\Library\Services\JsonValidator

    # API
    #orderware.responder:
    #    class: Orderware\AppBundle\Library\Services\Responder
    #    arguments: [@jms_serializer, @request_stack]

    # Orders
    #orderware.order_loader:
    #    class: Orderware\AppBundle\Library\Orders\Loader
    #    arguments: [@doctrine.orm.orderware_entity_manager]

    #orderware.order_importer:
    #    class: Orderware\AppBundle\Library\Orders\Importer
    #    arguments: [@doctrine.orm.orderware_entity_manager, @validator]

    # Feeds
    orderware.feeds.filesystem:
        class: Orderware\AppBundle\Library\Feeds\Filesystem
        arguments: ~

    orderware.feeds.processor:
        class: Orderware\AppBundle\Library\Feeds\Processor
        arguments: ["@service_container"]

    orderware.feeds.validator:
        class: Orderware\AppBundle\Library\Feeds\Validator
        arguments: ["@kernel"]

    orderware.feeds.catalog_feed_processor:
        class: Orderware\AppBundle\Library\Feeds\Processors\CatalogFeedProcessor
        arguments: ["@doctrine.orm.orderware_entity_manager"]
